account/urls.py
from django.urls import path
from django.contrib.auth.views import (LoginView, PasswordResetView, PasswordResetConfirmView)
from django.views.generic import TemplateView

from . import views
from .forms import (LoginForm, PwdResetForm, PwdResetConfirmForm)

app_name = 'account'

urlpatterns = [
	# login
	path("login/", views.CustomLoginView.as_view(
		template_name='account/user/login.html', 
		form_class=LoginForm
	), name="login"),
	# logout
	path("logout/", views.logout_view, name="logout"),
	# register
	path('register/', views.register, name='register'),
	# account activation
	path('activate/<slug:uid64>/<slug:token>/', views.account_activate, name='activate'),
	# password reset
	path('password_reset/', PasswordResetView.as_view(
		template_name='account/pwd_reset/password_reset.html',
		success_url='password_reset/password_reset_email_confirm/',
		email_template_name='account/pwd_reset/password_reset_email.html',
		form_class=PwdResetForm
		), name='pwd_reset'),
	# password reset email confirm
	path('password_reset/password_reset_email_confirm/', views.CustomLoginView.as_view(
		template_name='account/user/login.html', 
		form_class=LoginForm
		), name='password_reset_done'),
	# password reset confirm
	path('password_reset_confirm/<slug:uidb64>/<slug:token>/', PasswordResetConfirmView.as_view(
		template_name='account/pwd_reset/password_reset_confirm.html',
		success_url='password_reset_complete/',
		form_class=PwdResetConfirmForm
		), name='pwd_reset_confirm'),
	# password reset complete
	path('password_reset_confirm/MTA/set-password/password_reset_complete/', views.CustomLoginView.as_view(
		template_name='account/user/login.html', 
		form_class=LoginForm
		), name='password_reset_complete'),

	# user dashboard
	path('dashboard/', views.dashboard, name='dashboard'),
	# profile update
	path('profile/edit/', views.edit_details, name='edit_details'),
	# profile delete
	path('profile/delete/user/', views.delete_user, name='delete_user'),
	# profile delete confirmation
	path('profile/delete_confirm/', TemplateView.as_view(template_name='account/user/delete_confirm.html'), name='delete_confirm'),
	# wishlist
	path('wishlist/', views.WishlistView.as_view(), name="wishlist"),
	path('wishlist/add_to_wishlist/<slug:slug>/', views.Add_to_wishlist_view, name="add-to-wishlist"),
]

basket/urls.py
from django.urls import path

from . import views


app_name = 'basket'

urlpatterns = [
	path('', views.basket_summary, name='basket_summary'),
	path('update/', views.basket_update, name='basket_update'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("store.urls", namespace="store")),
    path("account/", include("account.urls", namespace="account")),
    path("basket/", include("basket.urls", namespace="basket")),
    path("more/", include("more.urls", namespace="more")),
    path("order/", include("order.urls", namespace="order")),
    path("address/", include("address.urls", namespace="address")),
    path("checkout/", include("checkout.urls", namespace="checkout")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path

from . import views

app_name = 'order'

urlpatterns = [
	path('remove-from-cart/<slug>/', views.remove_from_cart, name='remove-from-cart'),
	path('order_placement/', views.Order_placement, name='order-placement'),
	# orders history
	path('orders-history/', views.orders_history, name="orders-history"),
	# order cancel
	path('cancel-order/', views.order_cancel, name='order-cancel'),
	# order item cancel/remove
	path('order-item-remove/', views.order_item_remove, name='order-item-remove'),
]

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
	# Home Url
	path('', views.HomeView.as_view(), name='index'),
	# Category Url
	path('category/<slug:category_slug>/', views.CategoryListView.as_view(), name='products-by-category'),
	# Features Url
	# path('?featured-products', views.FeaturedCategoryListView.as_view(), name='product-by-featured-categories'),
	# Material Url
	path('material/<slug:material_slug>/', views.MaterialListView.as_view(), name='products-by-material'),
	# # Brand Url
	# path('brands/', views.BrandsListView.as_view(), name='products-by-brands'),
	# # Brand Individual Url
	# path('brand/<slug:brand_slug>/', views.BrandProductListView.as_view(), name='products-by-brand'),
	# Create Product Url
	path('product/<slug>/', views.ItemDetailView.as_view(), name='product'),
	# About Us
	path('about-us/', views.AboutUsView, name='about-us'),
]

templates/components/footer.html
{% load static %}

<footer class="container-fluid mt-5 pt-5">
	<div class="row align-items-center gap-2 px-xl-5 pt-5">
		<div class="col-lg-3 col-md-12 mb-5 pe-3 pe-xl-5">
			<h5>Sign up for our newsletter</h5>
			<p>Subscribe now for exclusive updates, offers, and news delivered directly to your inbox!</p>
		</div>
		<div class="col-md-6 px-5">
			<form action="" class="text-center">
				<div class="form-group mb-3">
					<input type="email" class="form-control subscribe rounded-4 border-0 py-4" placeholder="Email Address"
						required="required" />
				</div>
				<div>
					<button class="btn btn-primary btn-block rounded-5 border-0 px-5 py-2" type="submit">Subscribe</button>
				</div>
			</form>
		</div>
		<div class="row col-md-3">
			<div class="col mb-5">
				<h5 class="font-weight-bold mb-4">About</h5>
				<div class="d-flex flex-column justify-content-start">
					<a class="mb-2 footer-link" href="index.html">Our Story</a>
					<a class="mb-2 footer-link" href="contact.html">Contact Us</a>
					<a class="mb-2 footer-link" href="checkout.html">Size Chart</a>
				</div>
			</div>
			<div class="col mb-5">
				<h5 class="font-weight-bold mb-4">Information</h5>
				<div class="d-flex flex-column justify-content-start">
					<a class="mb-2 footer-link" href="index.html">Shipping Policy</a>
					<a class="mb-2 footer-link" href="detail.html">Terms of Service</a>
					<a class="mb-2 footer-link" href="cart.html">Privacy Policy</a>
				</div>
			</div>
		</div>
	</div>
	<!-- <div class="row border-top border-light mx-xl-5 py-4"> -->
		<!-- <div class="col-md-6 px-xl-0 text-center text-md-right">
			<img class="img-fluid" src="{% static 'store/img/payments.png' %}" alt="">
		</div> -->
	</div>
</footer>
<p class="text-center text-md-left footer-rights py-4 mb-0">
	&copy; 2024 Zubies. All Rights Reserved.
	<!-- Designed
	by
	<a class="font-weight-semi-bold" href="https://KTS Wizards.com">KTS Wizards</a><br> -->
</p>

templates/components/navbar.html
{% load static %}

<div class="container-fluid navbar-custom z-3">
	<div class="row align-items-center my-0 px-xl-5">
		<div class="col">
			<!-- <a href="{% url 'store:index' %}" class="text-decoration-none">
				<h1 class="m-0 display-5 font-weight-semi-bold logo-header">
					ZUBIES
				</h1>
			</a> -->
			<nav class="navbar navbar-expand-lg bottom-navbar navbar-light py-3 py-lg-2 px-0">
				<a href="" class="text-decoration-none d-block d-lg-none">
					<h1 class="m-0 display-5 font-weight-semi-bold text-uppercase logo-header">Zubies</h1>
				</a>
				<button type="button" class="navbar-toggler" data-toggle="collapse"
					data-target="#navbarCollapse">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarCollapse">
					<div class="navbar-nav col-md-10 m-md-auto d-flex justify-content-around align-items-center py-0">
						<a href="{% url 'store:products-by-category' category_slug='men' %}" class="nav-item nav-link">Men</a>
						<a href="{% url 'store:products-by-category' category_slug='women' %}" class="nav-item nav-link">Women</a>
						<a href="{% url 'store:products-by-category' category_slug='jackets' %}" class="nav-item nav-link">Jackets</a>
						<a href="{% url 'store:index' %}" class="nav-item nav-link font-weight-semi-bold logo-header">
							<img src="{% static 'img/brown-zubies-transparent background.webp' %}" width="150" alt="">
						</a>
						<a href="{% url 'store:products-by-category' category_slug='bags' %}" class="nav-item nav-link">Bags</a>
						<a href="{% url 'store:products-by-category' category_slug='shoes' %}" class="nav-item nav-link">Shoes</a>
						<a href="{% url 'store:products-by-category' category_slug='stilettos' %}" class="nav-item nav-link">Stilettos</a>
					</div>
				</div>
			</nav>
		</div>
		<div class="col-lg-1 col-4 text-end" style="min-width: fit-content;">
			<span class="dropdown">
				<a href="#" class="text-black text-decoration-none" role="button" data-bs-toggle="dropdown" data-bs-auto-close="true" aria-expanded="false">
					<svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" class="bi bi-person" viewBox="0 0 16 16">
						<path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6m2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0m4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4m-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10s-3.516.68-4.168 1.332c-.678.678-.83 1.418-.832 1.664z"/>
					</svg>
					<!-- <span class="badge">0</span> -->
				</a>
				<ul class="dropdown-menu dropdown-menu-dark mt-2 bg-black">
					<li><a class="dropdown-item" href="{% url 'account:dashboard' %}">Dashboard</a></li>
					<!-- <li><a class="dropdown-item" href="{% url 'order:orders-history' %}">Order History</a></li> -->
					<li><hr class="dropdown-divider bg-light"></li>
					{% if user.is_authenticated %}
						<li><a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a></li>
					{% else %}
						<li><a class="dropdown-item" href="{% url 'account:login' %}">Login</a></li>
						<li><a class="dropdown-item" href="{% url 'account:register' %}">Register</a></li>
					{% endif %}
				</ul>
			</span>
			<a href="{% url 'account:wishlist' %}" class="text-black text-decoration-none">
				<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-suit-heart" viewBox="0 0 16 16">
					<path d="m8 6.236-.894-1.789c-.222-.443-.607-1.08-1.152-1.595C5.418 2.345 4.776 2 4 2 2.324 2 1 3.326 1 4.92c0 1.211.554 2.066 1.868 3.37.337.334.721.695 1.146 1.093C5.122 10.423 6.5 11.717 8 13.447c1.5-1.73 2.878-3.024 3.986-4.064.425-.398.81-.76 1.146-1.093C14.446 6.986 15 6.131 15 4.92 15 3.326 13.676 2 12 2c-.777 0-1.418.345-1.954.852-.545.515-.93 1.152-1.152 1.595zm.392 8.292a.513.513 0 0 1-.784 0c-1.601-1.902-3.05-3.262-4.243-4.381C1.3 8.208 0 6.989 0 4.92 0 2.755 1.79 1 4 1c1.6 0 2.719 1.05 3.404 2.008.26.365.458.716.596.992a7.6 7.6 0 0 1 .596-.992C9.281 2.049 10.4 1 12 1c2.21 0 4 1.755 4 3.92 0 2.069-1.3 3.288-3.365 5.227-1.193 1.12-2.642 2.48-4.243 4.38z"/>
				</svg>
				<!-- <span class="badge">0</span> -->
			</a>
			<a href="{% url 'basket:basket_summary' %}" class="text-black text-decoration-none ms-1">
				<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-bag" viewBox="0 0 16 16">
					<path d="M8 1a2.5 2.5 0 0 1 2.5 2.5V4h-5v-.5A2.5 2.5 0 0 1 8 1m3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4zM2 5h12v9a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1z"/>
				</svg>
				<!-- <span class="badge">0</span> -->
			</a>
		</div>
	</div>
</div>