address/urls.py
from django.urls import path

from . import views

app_name = 'address'

urlpatterns = [
	path("", views.AddressListView, name="addresses"),
	path("session_update", views.AddressSessionView, name="address-session-update"),
	path("add/", views.add_address, name="add_address"),
	path("edit/<uuid:id>", views.edit_address, name="edit_address"),
	path("delete/<uuid:id>", views.delete_address, name="delete_address"),
	path("set_default/<uuid:id>", views.default_address, name="set_default"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("store.urls", namespace="store")),
    path("account/", include("account.urls", namespace="account")),
    path("basket/", include("basket.urls", namespace="basket")),
    path("more/", include("more.urls", namespace="more")),
    path("order/", include("order.urls", namespace="order")),
    path("address/", include("address.urls", namespace="address")),
    path("checkout/", include("checkout.urls", namespace="checkout")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
	# Home Url
	path('', views.HomeView.as_view(), name='index'),
	# Category Url
	path('category/<slug:category_slug>/', views.CategoryListView.as_view(), name='products-by-category'),
	# Features Url
	# path('?featured-products', views.FeaturedCategoryListView.as_view(), name='product-by-featured-categories'),
	# Material Url
	path('material/<slug:material_slug>/', views.MaterialListView.as_view(), name='products-by-material'),
	# # Brand Url
	# path('brands/', views.BrandsListView.as_view(), name='products-by-brands'),
	# # Brand Individual Url
	# path('brand/<slug:brand_slug>/', views.BrandProductListView.as_view(), name='products-by-brand'),
	# Create Product Url
	path('product/<slug>/', views.ItemDetailView.as_view(), name='product'),
	# About Us
	path('about-us/', views.AboutUsView, name='about-us'),
]

address/models.py
import uuid
from django.db import models
from django.utils.translation import gettext_lazy as _
from django_countries.fields import CountryField

# Create your models here.

class BillingAddress (models.Model):
	CITY_CHOICES = (
		("", "City"),
		("abd", "Attock"),
		("abt", "Abbottabad"),
		("bhr", "Bahawalnagar"),
		("bwn", "Bhawana"),
		("bhk", "Bhakkar"),
		("bwp", "Bahawalpur"),
		("cwp", "Chishtian"),
		("dgh", "Dera Ghazi Khan"),
		("dnb", "Dinawali"),
		("dip", "Dipalpur"),
		("fdr", "Fateh Jhang"),
		("fsl", "Faisalabad"),
		("ghk", "Gujar Khan"),
		("gjr", "Gujranwala"),
		("grk", "Gwadar"),
		("grw", "Gujranwala"),
		("gjr", "Gujrat"),
		("hyd", "Hyderabad"),
		("isl", "Islamabad"),
		("jlm", "Jalalpur"),
		("jwn", "Jaranwala"),
		("jwp", "Jhelum"),
		("khr", "Khairpur"),
		("khi", "Karachi"),
		("khr", "Khanewal"),
		("ktt", "Kotli"),
		("kwb", "Kot Adu"),
		("lai", "Lalamusa"),
		("lhr", "Lahore"),
		("ldr", "Lodhran"),
		("lrd", "Larkana"),
		("ltr", "Layyah"),
		("mll", "Mian Channu"),
		("mlk", "Malakwal"),
		("mlt", "Mardan"),
		("mrd", "Multan"),
		("mnt", "Mansehra"),
		("mgw", "Mandi Bahauddin"),
		("mwm", "Mianwali"),
		("mtr", "Multan"),
		("mzt", "Murree"),
		("mzw", "Muzaffargarh"),
		("ngt", "Narowal"),
		("nwn", "Nankana Sahib"),
		("pwp", "Peshawar"),
		("phl", "Pattoki"),
		("qta", "Quetta"),
		("qrb", "Quetta Residency"),
		("rch", "Rajanpur"),
		("rnw", "Rawalpindi"),
		("rkn", "Rahim Yar Khan"),
		("rwp", "Rawalpindi"),
		("sgr", "Sargodha"),
		("skt", "Sialkot"),
		("shw", "Sheikhupura"),
		("swn", "Swat"),
		("sak", "Sargodha"),
		("sbq", "Sahiwal"),
		("ska", "Sakrand"),
		("skz", "Sukheki"),
		("stw", "Sialkot"),
		("suk", "Sukkur"),
		("swl", "Sahiwal"),
		("sgr", "Sargodha"),
		("swl", "Sialkot"),
		("saw", "Sawat"),
		("ttn", "Toba Tek Singh"),
		("vhn", "Vehari"),
		("wah", "Wah Cantt"),
		("wln", "Wazirabad"),
	)

	id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	# Customer
	customer = models.ForeignKey("account.User", on_delete=models.CASCADE, verbose_name=_("Customer"), blank=True, null=True)
	first_name = models.CharField(_("First Name"), max_length=150)
	last_name = models.CharField(_("Last Name"), max_length=150)
	email = models.EmailField()
	# Delivery Details
	phone_number = models.CharField(_("Phone Number"), max_length=15)
	address_line_1 = models.CharField(_("Address Line 1"), max_length=150)
	address_line_2 = models.CharField(_("Address Line 2"), max_length=150, blank=True)
	city = models.CharField(_("City"), choices=CITY_CHOICES, max_length=150)
	state = models.CharField(_("State/Province"), max_length=150)
	country = CountryField(_("Country"), blank_label='Country', default='PK')
	zip_code = models.CharField(_("Zip Code"), max_length=12)
	default = models.BooleanField(_("Default"), default=False)

	class Meta:
		verbose_name = 'Billing Address'
		verbose_name_plural = 'Billing Addresses'

	def __str__(self):
		return self.customer.username

address/forms.py
from django import forms

from account.models import User

from .models import BillingAddress


class UserAddressForm(forms.ModelForm):
	class Meta:
		model = BillingAddress
		fields = "__all__"
		exclude = ("customer", "default")

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		for field_name in self.fields:
			self.fields[field_name].widget.attrs.update(
				{
					"class": "form-control mb-2",
					"placeholder": field_name.replace("_", " ").title(),
				}
			)
		self.fields["country"].widget.attrs.update(
			{
				"class": "form-select",
			}
		)
		self.fields["city"].widget.attrs.update(
			{
				"class": "form-select",
			}
		)


class BillingForm(forms.ModelForm):
	first_name = forms.CharField(
		label="First Name",
		min_length=4,
		max_length=50,
		widget=forms.TextInput(
			attrs={
				"class": "form-control",
				"placeholder": "First Name",
			}
		),
	)
	last_name = forms.CharField(
		label="Last Name",
		min_length=4,
		max_length=50,
		widget=forms.TextInput(
			attrs={
				"class": "form-control",
				"placeholder": "Last Name",
			}
		),
	)
	email = forms.EmailField(
		label="Email",
		max_length=200,
		widget=forms.EmailInput(
			attrs={
				"class": "form-control mb-3",
				"placeholder": "email",
			}
		),
	)
	save_info = forms.BooleanField(
		label="Save this information for next time",
		required=False,
		widget=forms.CheckboxInput(),
	)
	PAYMENT_CHOICES = [
		("COD", "Cash on Delivery"),
	]

	payment_method = forms.ChoiceField(
		choices=PAYMENT_CHOICES,
		widget=forms.RadioSelect(
			attrs={
				"checked": "checked",
			}
		),
	)

	class Meta:
		model = BillingAddress
		fields = "__all__"
		exclude = ("user",)

		labels = {
			"address_line_1": "Address",
			"address_line_2": "Address 2",
			"state": "State/Province/Region",
		}

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		self.fields["phone_number"].widget.attrs.update(
			{
				"class": "form-control",
				"placeholder": "Phone number",
			}
		)
		self.fields["address_line_1"].widget.attrs.update(
			{
				"class": "form-control",
				"placeholder": "Address",
			}
		)
		self.fields["address_line_2"].widget.attrs.update(
			{"class": "form-control", "placeholder": "Address 2"}
		)
		self.fields["city"].widget.attrs.update(
			{"class": "form-select", "placeholder": "City"}
		)
		self.fields["state"].widget.attrs.update(
			{"class": "form-control", "placeholder": "State"}
		)
		self.fields["country"].widget.attrs.update(
			{"class": "form-select", "placeholder": "Country"}
		)
		self.fields["zip_code"].widget.attrs.update(
			{"class": "form-control", "placeholder": "Zip Code"}
		)

address/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import (render, redirect, get_object_or_404, HttpResponseRedirect, reverse)

from .billingaddress import Billing
from .forms import UserAddressForm
from .models import BillingAddress

# Create your views here.
def AddressView(request):
	return BillingAddress.objects.filter(customer=request.user)

@login_required
def AddressSessionView(request):
	billing_session = Billing(request)
	if request.POST.get('action') == 'post':
		address = BillingAddress.objects.get(customer=request.user, default=True)
		billing_session.addBillingObject(address=address, uid=request.user.id)
	response = JsonResponse('successfully added address', safe=False)
	return response

@login_required
def AddressListView(request):
	addresses = BillingAddress.objects.filter(customer=request.user)
	return render(request, "address/addresses.html", {
		'addresses': addresses,
	})

@login_required
def add_address(request):
	if request.POST:
		address_form = UserAddressForm(request.POST)
		if address_form.is_valid():
			address_form = address_form.save(commit=False)
			address_form.customer = request.user
			address_form.save()
			messages.success(request, 'New Delivery Address has been added')
			return redirect('address:addresses')
		else:
			return render(request, 'address/add', {
				'form': address_form
			})

	address_form = UserAddressForm()
	return render(request, 'address/add.html', {
		'form': address_form
	})

@login_required
def edit_address(request, id):
	address = BillingAddress.objects.get(pk=id, customer=request.user)
	if request.POST:
		address_form = UserAddressForm(request.POST, instance=address)
		if address_form.is_valid():
			address_form.save()
			return redirect('address:addresses')
		else:
			return render(request, 'address/add', {
				'form': address_form
			})

	address_form = UserAddressForm(instance=address)
	return render(request, 'address/add.html', {
		'form': address_form
	})

@login_required
def delete_address(request, id):
	try:
		BillingAddress.objects.get(pk=id, customer=request.user).delete()
		messages.success(request, 'Address successfully deleted.')
	except ObjectDoesNotExist:
		messages.error(request, 'Address doesn\'t exist.')
	return redirect('address:addresses')


@login_required
def default_address(request, id):
	try:
		address = BillingAddress.objects.get(pk=id, customer=request.user)
		BillingAddress.objects.filter(customer=request.user).update(default=False)
		address.default = True
		address.save()
	except ObjectDoesNotExist:
		messages.error(request, 'Error: Address doesn\'t exist.')
	return redirect('address:addresses')

templates/address/add.html
{% extends 'store/layout.html' %}
{% load static %}

{% block title %}Sign Up{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/store/forms.css' %}">
{% endblock style %}

{% block body %}
<div class="container-fluid">
	<div class="row no-gutter">
		<div class="col-md-12">
			<div class="d-flex align-items-center py-4 pb-5">
				<div class="container">
					<div class="row">
						<div class="auth_form col-12 col-lg-8 mx-auto">
							<form action="" class="rounded mx-auto p-4 col-lg-10" method="post">
								{% csrf_token %}
								<h3 class="mb-2">Add Address</h3>
								<p class="mb-4 text-muted">Add a new delivery address and delivery preferences.</p>

								{% if form.errors %}
								<p class="text-danger">Please correct the following errors:</p>
								{% for field in form %}
								{% if field.errors %}
								<div class="alert alert-danger alert-dismissible fade show" role="alert">
									{{ field.label }}: {{ field.errors | striptags }}
									<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
								</div>
								{% endif %}
								{% endfor %}
								{% endif %}

								<div class="row">
									<div class="col">
										<label for="id_first_name">{{ form.first_name.label }}</label>
										{{ form.first_name }}
									</div>
									<div class="col">
										<label for="id_last_name">{{ form.last_name.label }}</label>
										{{ form.last_name }}
									</div>
								</div>
								<div class="row">
									<div class="col">
										<label for="id_email">{{ form.email.label }} <span class="text-muted small">(Optional)</span></label>
										{{ form.email }}
									</div>
									<div class="col">
										<label for="id_phone_number">{{ form.phone_number.label }}</label>
										{{ form.phone_number }}
									</div>
								</div>
								<div class="row">
									<div class="col">
										<label for="id_address_line_1">{{ form.address_line_1.label }}</label>
										{{ form.address_line_1 }}
									</div>
									<div class="col">
										<label for="id_address_line_2">{{ form.address_line_2.label }} <span class="text-muted small">(Optional)</span></label>
										{{ form.address_line_2 }}
									</div>
								</div>
								<div class="row">
									<div class="col">
										<label for="id_city">{{ form.city.label }}</label>
										{{ form.city }}
									</div>
									<div class="col">
										<label for="id_state">{{ form.state.label }}</label>
										{{ form.state }}
									</div>
									<div class="col">
										<label for="id_country">{{ form.country.label }}</label>
										{{ form.country }}
									</div>
									<div class="col">
										<label for="id_zip_code">{{ form.zip_code.label }}</label>
										{{ form.zip_code }}
									</div>
								</div>
								<input class="btn w-100" type="submit" value="Save">
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

templates/address/addresses.html
{% extends 'store/layout.html' %}
{% load static %}

{% block title %}Addresses{%endblock %}

{% block style %}
	<link rel="stylesheet" href="{% static 'css/address/card.css' %}" />
{% endblock %}

{% block body %}
<div class="container mb-3">
	<div class="hstack gap-3">
		<!-- <a href="{% url 'store:index' %}" class="link-body-emphasis">
				<img src="{% static 'store/imgs/icon/sanwal2.webp' %}" alt="Logo" width="50" height="45">
			</a> -->
		<!-- <div class="col"> -->
		<h1 class="h5 mb-0">Your Addresses</h1>
		<div class="vr"></div>
		<div class="text-muted">
			Manage your addresses and delivery preferences
		</div>
		<!-- </div> -->
	</div>
	<hr />
	<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
		<div {% if addresses|length == 0 %} class="col mx-auto add-address" {% endif %} class="col add-address">
			<a
				href="{% url 'address:add_address' %}"
				class="text-reset"
				role="button"
			>
				<div class="card mb-3 h-100 rounded-4">
					<div class="row g-0 h-100">
						<div class="col-12">
							<div
								class="card-body text-center position-absolute top-50 start-50 translate-middle"
							>
								<svg
									xmlns="http://www.w3.org/2000/svg"
									width="60"
									height="60"
									fill="currentColor"
									class="bi bi-plus"
									viewBox="0 0 16 16"
								>
									<path
										d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5"
									></path>
								</svg>
								<h1 class="h5">Add Address</h1>
							</div>
						</div>
					</div>
				</div>
			</a>
		</div>
		{% for address in addresses %}
		<div class="col h-100">
			<div
				{% if address.default %}
				class="card default h-100 px-3 pb-3 rounded-4"
				{% endif %}
				class="card h-100 px-3 rounded-4"
			>
				<div class="card-header small text-muted text-center">
					{% if address.default %} Default {% endif %}
				</div>
				<div class="card-body small py-1">
					<p class="card-text m-0 fw-bold">
						{{ address.first_name }} {{ address.last_name }}
					</p>
					<p class="card-text m-0">{{ address.phone_number }}</p>
					<p class="card-text m-0">{{ address.email }}</p>
					<p class="card-text m-0">{{ address.address_line_1 }}</p>
					<p class="card-text m-0">{{ address.address_line_2 }}</p>
					<p class="card-text m-0">{{ address.zip_code }}</p>
					<p class="card-text m-0">{{ address.city }}</p>
					<p class="card-text m-0">
						{{ address.get_country_display }}
					</p>
					<div class="pt-3 hstack gap-3 justify-content-center">
						<a href="{% url 'address:edit_address' address.id %}">Edit</a>
						<div class="vr"></div>
						<a href="{% url 'address:delete_address' address.id %}">Delete</a>

						{% if not address.default %}
							<div class="vr"></div>
							<a href="{% url 'address:set_default' address.id %}" class="text-decoration-none">Set Default</a>
						{% endif %}
					</div>
				</div>
			</div>
		</div>
		{% endfor %}
	</div>
</div>
{% endblock %}